unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'cesarferreira/tmux.expose'

set -g @continuum-restore 'on'
set -g @tmux-expose-command 'tmux-expose --columns 2'
set -g @tmux-expose-height '50%'
set -g @tmux-expose-anchor 'bottom'

run '~/.tmux/plugins/tpm/tpm'
