unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'timvw/tmux-assistant-resurrect'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
